apiVersion: v1
kind: Service
metadata:
  name: transaction-metrics-service
  labels:
    app: transaction-metrics
spec:
  selector:
    app: transaction-metrics
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
