# prometheus/prometheusApplication.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    #chart from helm
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.30.1
      helm:
        valueFiles:
          - $values/prometheus/values.yaml

    #values from git
    - repoURL: 'https://github.com/PNC-SRE-Capstone-Team/SRE-Capstone'
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
    backoff:
      duration: 5s
      maxDuration: 3m0s
      factor: 2