#prometheus/values.yaml
server:
  service:
    type: LoadBalancer
    servicePort: 30447

extraScrapeConfigs:
  - job_name: "argocd-server"
    metrics_path: /metrics
    static_configs:
      - targets: ['argo-cd-argocd-server.argocd.svc.cluster.local:8083']


