architecture: standalone

# MongoDB service configuration
service:
  type: LoadBalancer
  port: 30445



# Persistent storage settings
persistence:
  enabled: true
  size: 8Gi

# Disable replica set
replicaSet:
  enabled: false

metrics:
  enabled: true