architecture: standalone

tls:
  enabled: false

# MongoDB service configuration
service:
  type: loadBalancer
  ports:
    mongodb: 27017

# Persistent storage settings
persistence:
  enabled: true
  size: 8Gi

# Disable replica set
replicaSet:
  enabled: false

metrics:
  enabled: true

#extraFlags:
#  --setParameter tlsUseSystemCA=true

