# MongoDB service configuration
service:
  type: LoadBalancer
  port: 30445

# Authentication settings
auth:
  enabled: true
  database: default

# Persistent storage settings
persistence:
  enabled: true
  size: 8Gi

# Disable replica set
replicaSet:
  enabled: false