architecture: standalone

tls:
  mTLS: 
    enabled: false
  enabled: true
  mode: allowTLS


# MongoDB service configuration
service:
  type: ClusterIP
  ports:
    mongodb: 30445

# Persistent storage settings
persistence:
  enabled: true
  size: 8Gi

# Disable replica set
replicaSet:
  enabled: false

metrics:
  enabled: true

extraFlags:
  --setParameter tlsUseSystemCA=true

