#nginx/values.yaml
ingress-nginx:
  controller:
    # sole loadbalancer service for cluster, all others will be accessed via cluster IP through ingress-nginx
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local

    #Metrics for prometheus
    metrics:
      enabled: true
    prometheusRule:
      enabled: true

  rbac:
    create: true
