argo-cd: 
  server:
    service:
      type: LoadBalancer

      servicePortHttpsName: https
      servicePortHttps: 30443

    configs:
      rbac:
        policy.csv: |
          p, role:admin, applications, *, */*, allow
          g, admin, role:admin
        policy.default: role:readonly

    # Disable Ingress in ArgoCD as we are using LoadBalancer
    ingress:
      enabled: false

  # additional config
  applicationController:
    replicas: 1
  dex:
    enabled: false
  notifications:
    enabled: true