argo-cd: 
  server:
    service:
      type: LoadBalancer
      servicePortHttpsName: https
      servicePortHttps: 30443
      servicePortHttpName: https
      servicePortHttp: 30442
      
    # Disable Ingress in ArgoCD as we are using LoadBalancer
    ingress:
      enabled: false

  configs:
    rbac:
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, get, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, logs, get, *, allow
        p, role:admin, exec, create, */*, allow
        g, admin, role:admin
      policy.default: role:readonly


  # additional config
  applicationController:
    replicas: 1
  dex:
    enabled: false
  notifications:
    enabled: true