server:
  service:
    type: LoadBalancer

    servicePortHttpsName: https
    servicePortHttps: 30443

  config:
    initialAdminPassword: ""  # Leave empty to respect the existing admin password in argocd-admin-secret

   # Disable Ingress in ArgoCD as we are using LoadBalancer
  ingress:
    enabled: false

# additional config
applicationController:
  replicas: 1
dex:
  enabled: false
notifications:
  enabled: true