argo-cd: 
  global:
    domain: argo.damdiel.com
  certificate: 
    enabled: true

  server:
    service:
      type: LoadBalancer
      servicePortHttpsName: https
      servicePortHttps: 30443
      servicePortHttpName: http
      servicePortHttp: 30442
      
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true

  configs:
    params:
      server.insecure: true
    rbac:
      policy.csv: |
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, get, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, logs, get, *, allow
        p, role:admin, exec, create, */*, allow
        g, admin, role:admin
      policy.default: role:readonly


  # additional config
  applicationController:
    replicas: 1
  dex:
    enabled: false
  notifications:
    enabled: true