# Server (argocd-server) settings
server:
  service:
    type: LoadBalancer          # Expose ArgoCD externally via LoadBalancer
    port: 30443                 # External HTTPS port (without SSL cert management by ArgoCD)
    targetPort: 8080            # Internal HTTPS port for ArgoCD's server

  # Configure URL for external HTTPS access, though internal communication uses HTTP
  config:
    url: https://argocd-server.argocd.svc.cluster.local  # Internal URL for ArgoCD over HTTPS without SSL certs
    initialAdminPassword: ""  # Leave empty to respect the existing admin password in argocd-admin-secret

  # Disable Ingress in ArgoCD as we are using LoadBalancer
  ingress:
    enabled: false

# additional config
applicationController:
  replicas: 1
dex:
  enabled: false
notifications:
  enabled: true