apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.0.0
    helm:
      valueFiles:
        - values/mariadb/values.yaml  # Ensure this path exists in the repo

    # External values from Git
    additionalSources:
      - repoURL: 'https://github.com/PNC-SRE-Capstone-Team/SRE-Capstone'
        targetRevision: chad

  destination:
    server: https://kubernetes.default.svc
    namespace: database
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
    backoff:
      duration: 5s
      maxDuration: 3m0s
      factor: 2
