externalAccess:
  enabled: true
  broker:
    service:
      type: NodePort
      ports:
        external: 9094
      externalIPs: |
        10.100.200.32
        10.100.200.33
        10.100.200.35
  controller:
    service:
      type: NodePort
      containerPorts:
        external: 9094
      externalIPs: |
        10.100.200.32
        10.100.200.33
        10.100.200.35

serviceAccount:
  create: true
rbac:
  create: true
controller:
  automountServiceAccountToken: true
  replicaCount: 1
broker:
  automountServiceAccountToken: true
  pdb:
    create: false
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

auth:
  interBrokerProtocol: plaintext
  clientProtocol: plaintext
