externalAccess:
  enabled: true
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094
      loadBalancerIPs: [10.100.200.32, 10.100.200.33, 10.100.200.35]
  controller:
    service:
      type: LoadBalancer
      containerPorts:
        external: 9094
      loadBalancerIPs: [10.100.200.32, 10.100.200.33, 10.100.200.35]
serviceAccount:
  create: true
rbac:
  create: true
controller:
  automountServiceAccountToken: true
  replicaCount: 3
broker:
  automountServiceAccountToken: true
  pdb:
    create: false
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

auth:
  interBrokerProtocol: plaintext
  clientProtocol: plaintext
