name: deploy-kafkasendlogs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main", "kafka"]
    paths:
      - kafkaSendLogs/**
      - .github/workflows/deploy-kafkasendlogs.yml
  pull_request:
    branches: ["main"]
    paths:
      - kafkaSendLogs/**
      - .github/workflows/deploy-kafkasendlogs.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy_kafkaSendLogs:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /home/op/actions-runner/_work/SRE-Capstone/SRE-Capstone/*

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Build the image
        run: |
          cd ./kafkaSendLogs
          docker login --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINER_REGISTRY_TOKEN }} ghcr.io
          sudo docker build . -t ghcr.io/pnc-sre-capstone-team/kafkasendlogs:latest
          sudo docker push ghcr.io/pnc-sre-capstone-team/kafkasendlogs:latest
      - name: Deploy with ArgoCD CLI
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app create -f kafkaSendLogs/kafkaSendLogsApplication.yml --upsert
