name: deploy-kafka

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main", "kafka"]
    paths:
      - kafka/**
      - .github/workflows/deploy-kafka.yml
  pull_request:
    branches: ["main"]
    paths:
      - kafka/**
      - .github/workflows/deploy-kafka.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-kafka:
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /home/op/actions-runner/_work/SRE-Capstone/SRE-Capstone/*

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Add helm repo with bitnami chart
        run: |
          sudo helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Deploy with ArgoCD CLI
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app create -f kafka/kafkaApplication.yaml --upsert
