name: deploy-kafkasendlogs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["main", "kafka"]
    paths:
      - kafkaSendLogs/**
      - .github/workflows/deploy-kafkasendlogs.yml
  pull_request:
    branches: ["main"]
    paths:
      - kafkaSendLogs/**
      - .github/workflows/deploy-kafkasendlogs.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          cd ./kafkaSendLogs
          sudo docker build . -t kafkasendlogs:latest
          sudo docker save kafkasendlogs:latest | sudo k3s ctr images import -
  deploy-kafkaSendLogs:
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /home/op/actions-runner/_work/SRE-Capstone/SRE-Capstone/*

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Deploy with ArgoCD CLI
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app create -f kafkaSendLogs/kafkaSendLogsApplication.yaml --upsert
