name: deploy-cert-manager

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main", "nginx" ]
    paths:
      - cert-manager/**
      - .github/workflows/deploy-cert-manager.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - cert-manager/**
      - .github/workflows/deploy-cert-manager.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-cert-manager:
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /home/op/actions-runner/_work/SRE-Capstone/SRE-Capstone/*

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false
            
      - name: Add helm repo
        run: |  
            sudo helm repo add jetstack https://charts.jetstack.io --force-update

      - name: Deploy with ArgoCD CLI
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app create -f cert-manager/cert-managerApplication.yaml --upsert
