name: deploy-argocd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main", "argocd" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-argocd:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            argocd
          clean: false


      - name: Apply ArgoCD Admin Password Secret
        env:
          ARGOCD_SECRET: ${{ secrets.ARGOCD_SECRET }}
        run: |
          echo "$ARGOCD_SECRET" | base64 --decode > argocd/argocd-admin-secret.yaml
          sudo kubectl apply -f argocd/argocd-admin-secret.yaml
          rm argocd/argocd-admin-secret.yaml  # Clean up after applying

      - name: Install or Upgrade ArgoCD with Helm
        run: |
          sudo helm repo add argo https://argoproj.github.io/argo-helm
          sudo helm dep update $GITHUB_WORKSPACE/argocd/
          sudo helm upgrade --install argo-cd $GITHUB_WORKSPACE/argocd/ -n "argocd" -f $GITHUB_WORKSPACE/argocd/values.yaml --create-namespace --kubeconfig /etc/rancher/k3s/k3s.yaml
  
      - name: Wait for ArgoCD to be ready
        run: |
          sudo kubectl wait --for=condition=available --timeout=600s deployment/argo-cd-argocd-server -n "argocd"
