name: deploy-ingress-nginx

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main", "argocd", "nginx" ]
    paths:
      - nginx/**
      - .github/workflows/deploy-ingress-nginx.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - nginx/**
      - .github/workflows/deploy-ingress-nginx.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-ingress-nginx:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'nginx'
          clean: false

      - name: Add helm repo
        run: |  
          sudo helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

      - name: Deploy with ArgoCD CLI
        run: |
          sudo argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          sudo argocd app create -f nginx/ingress-nginxApplication.yaml --upsert --helm-set controller.extraArgs.default-ssl-certificate="ingress-nginx/wildcart-cert-tls"
      
      - name: Apply ingress configurations
        run: |
          sudo kubectl apply -f $GITHUB_WORKSPACE/nginx/configurations/nginxIngress.yaml -n ingress-nginx
          sudo kubectl apply -f $GITHUB_WORKSPACE/nginx/configurations/argoIngress.yaml -n argocd
          sudo kubectl apply -f $GITHUB_WORKSPACE/nginx/configurations/monitoringIngress.yaml -n monitoring
          sudo kubectl apply -f $GITHUB_WORKSPACE/nginx/configurations/kafkaIngress.yaml -n kafka